version: "3.8"

services:
  posgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - posgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin 
      - ./pgadmin-data/sessions:/var/lib/pgadmin/sessions 
      - ./pgadmin-data/storage:/var/lib/pgadmin/storage
  

  